### ISSUE TITLE
Changes from #98 and #99 fails the pipeline

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#101]
@MadsNielsen the changes regarding Bundle and Gemfile.lock (I think) fails our pipeline when I merged in the changes from today.

Can you please look at it?

http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Praqmatic-Automated-Changelog%20pipeline/job/1_pretested-integration_pac/63/

I can the our first job, pretested, actually builds a snapshot version of the PAC Docker image, and then run rake tests inside it.
This means default behavior there needs to include rspec. I'm okay with including them in the image for now, if we make an issue on making the image smaller, and figuring out how to have a container we can use for testing and one for running later.

Pretested jobs run these:

```
docker build -t praqma/pac:snapshot .
docker run --entrypoint=/bin/sh --rm -v $(pwd):/data praqma/pac:snapshot -c rake test
```

Adn the release job builds the image again, using a docker build and push plugin.

**Comment by buep** [comment]
Changes are stuck on a ready branch here: https://github.com/Praqma/Praqmatic-Automated-Changelog/commits/ready/100-Gather-inputs-to-test-guidelines-from-colleagues-and-publish-in-documentation

**Comment by MadsNielsen** [comment]
Ahhh right :) i know what the problem is. 

The tests are run from inside the docker image...and we excluded the test gems for installation in the docker file...We'll need to include them if we want to run tests from inside.
