### ISSUE TITLE
Can't run in WSL

### ISSUE THREAD

**Issue by NKJensen** [Praqma/Praqmatic-Automated-Changelog#114]
Perhaps it is stating the obvious, but the examples can't run in WSL.

**Comment by bicschneider** [comment]
Please elaborate with commands and log-files/output

**Comment by bicschneider** [comment]
It works:
Install Docker via this link: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
.. and then run it
```docker run -v $(pwd | sed -e 's/mnt//'):/data --net=host praqma/pac:3.x.x-latest pac from 96025f592 --settings=/data/settings_pac-jira.yml```

**Comment by bicschneider** [comment]
Not an issue but document howto in #117
