### ISSUE TITLE
PAC 2.0 uses basic authentication against Jira - We should support Crowd as well

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#12]
Will that work with Jira if using crowd?

**Comment by buep** [comment]
@hoeghh @praqmaTim - @MadsNielsen is asking if there are any compatibility issues related to Jira is crowd is used?

Currently the PAC 2.0 is planned to use basic authentication.

**Comment by lakruzz** [comment]
Related to #16

**Comment by MadsNielsen** [comment]
I think this card should be about us supporting Crowd (we should). The Jira documentation has information about how this is supposed to be happening.

**Comment by buep** [comment]
Issues is about supporting authentication methods that is commonly used.

**Comment by MadsNielsen** [comment]
This has been tested and verified manually.

We've used the authentication with https https://www.atlassian.com (jira-cloud)

and also used it against our own instance running on zetta cloud.

**Comment by buep** [comment]
And there automated tests running against Jira, so agree this is fine. As long as we can login towards http and https.
Cool.
