### ISSUE TITLE
Create an environment where PAC can be built and run.

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#18]
See #9. We could do this using docker. 

We already have a pac-image re-use that. And use the image to run in a prepared environment.

**Comment by buep** [comment]
Adding to PAC Jira milestone, it is already planned functionality though you created a specific issue for it.

**Comment by MadsNielsen** [comment]
I think this resolves itself. We have a working docker image for executing pac, you just need to override the entry point and it can used to build and run PAC, it has ruby in it and the necessary dependencies. I think this can be resolved.

**Comment by buep** [comment]
You probably will need to update the readme, but then yes there is nothing except documentation to do. At least not if you resolved the things missing in #9 I just re-opened.
For example that I can't find our release of the container ... See comments: https://github.com/Praqma/Praqmatic-Automated-Changelog/issues/9#issuecomment-209649935

**Comment by buep** [comment]
How can I use the container you have build to run for example the rake tasks during development?

**Comment by MadsNielsen** [comment]
This was added to the README.md file: On how to run rake tests of PAC using the same container.
docker run --entrypoint=/bin/sh --rm -v $(pwd):/data praqma/pac:snapshot -c rake test

**Comment by buep** [comment]
Issues require a release pipeline for the docker image, but we are discussion solution and pro/cons.

I need both suggested solutions explained here in bullet points so we can decide.

**Comment by MadsNielsen** [comment]
There are two possible ways to solve this.

**Docker hub autobuild**
* Pros
 * Does not require any machine resources.
 * Nice and neat application links, markdown highlighed documentation on Dockerhub (automatically)
 * Easy to set up tagging
* Cons
 * Needs setup to notify if build failed
 * Cannot really be part of a pipeline, since the release should be a manual step...but this is done automatically. The autobuild only verifies that the image can be built but test is not part of this. 
 * We'll need to move pac to new repository and replace the existing pac repo with the autobuild repository if we wish to maintain the shorthand praqma/pac notation for the image.

**Manual**
* Pros
 * Very easy setup. We can borrow the publish step from existing DSL sources
 * Possible to use it as a part of our pipeline in a build step. 
 * We can verify the image that will be built before publish
* Cons
 * No nice documention on dockerhub. 
 * Requires machine resources

In both cases we want to maintain history of the dockerfile for the original images. For the autobuild @JKrag suggested moving and retagging all existing images under praqma/pac to praqma/pacenv, and in that case you'd also make a clone of the existing praqma/docker-pac repo under the new name praqma/docker-pacenv for posterity and historical reasons. 

For the manual procedure, we could simply put a note in the dockerfile pointing to the new location on github stating that starting from v. X.X.X the image was built from the official PAC repository and it's dockerfile: https://github.com/Praqma/Praqmatic-Automated-Changelog.

**Comment by JKrag** [comment]
The pipeline manual step part can easily be addressed by auto building the official release images from a release branch. 
Then we can set up a job in Jenkins that pulls the auto build images from master (triggered from hub) and verifies them before allowing manual release.

**Comment by MadsNielsen** [comment]
Job dsl now works with releases. Closing this.

**Comment by buep** [comment]
I persisted some of the research from this issue. Now I agree it can close.
