### ISSUE TITLE
research how to make a release for a ruby application

### ISSUE THREAD

**Issue by Ordojan** [Praqma/Praqmatic-Automated-Changelog#20]
To release PAC I need to know what are the general conventions for publishing a ruby application.

**Comment by Ordojan** [comment]
Couldn't find anything specific. Going to just package everything up and upload it.

**Comment by buep** [comment]
Upload it where?

What about tagging? Earlier release procedure for PAC was just to tag the release as it was used as a source (script)...

**Comment by MadsNielsen** [comment]
Github has support for both tagging the commit. And zipping the source as a binary release. It Even has a release API.

**Comment by buep** [comment]
Do you wan't to zip a set of scripts? Is that to avoid just pulling a tag from github or clicking the get tag as zip file?

**Comment by MadsNielsen** [comment]
Its easier to distribute a zip file. We decided to try doing it the 'github' way using their api.

**Comment by Ordojan** [comment]
@MadsNielsen  @buep  We were thinking of hosting the artifacts on GitHub and I can automate the deployment using the API they have [here](https://help.github.com/articles/creating-releases/#automatically-creating-releases). I was looking up if there was some sort of ruby way of packaging up an application. After posting the comment I found [this](http://phusion.github.io/traveling-ruby/). It's a way of bundling a ruby interpreter, plus dependencies in a neat little package so end users don't have to go through the process of installing everything themselves. They just have to extract and run the executor. Seems like you can also create rake tasks that will create packages for every OS.  [Here](https://github.com/phusion/traveling-ruby/blob/master/TUTORIAL-1.md) is the hello world tutorial they have. What do you think?

**Comment by buep** [comment]
Two comments:

* Earlier we released just by tagging the version we called release: https://github.com/Praqma/Praqmatic-Automated-Changelog/tags Without any further magic, there is still a downloadable zip/tar.gz file so I don't know what else I gain from the release?

* I don't like the traveling Ruby... why not use a container? We have earlier decided that PAC is going to be distributed two ways: as source code tagged with version on Github, and together with our docker-pack container (not inside it though).


So explain to me what you try to achieve with all this effort? What do we gain?

**Comment by Ordojan** [comment]
So you create a tag with a version number and GitHub will automatically zip it and it will appear in the release section? I've never done it so I'm not sure. 

I remember that docker didn't work on Windows, if that is still true I guess that is the only gain. I wanted to see if there was some sort of convention in the community for preparing applications for release. I understand that using both docker and traveling ruby would be a waste of time. I didn't know you guys had discussions about this already.

**Comment by buep** [comment]
No problem, I haven't been that obvious.

I suggest we take the following approach to our release, to follow what we already have been doing earlier and then log improvement for later.

This means the release process must:

* tag the repository with a version (which allows users to use that tagged version and download it)
* make sure the latest released version works with our Docker PAC container.

Then later improvement can be:

* distribute PAC in a container
* distribute is in a well know Ruby package (e.g. Gem or Travelling Ruby)

**Comment by MadsNielsen** [comment]
@buep Here is an example on how the 'releases' can look like in GitHub https://github.com/EmmittJ/PoESkillTree/releases

I don't know the API...i thought you could do something fancy with little effort :)

**Comment by buep** [comment]
What looks fancy on that link, is that there is a changelog - you can have that.
We just don't have a binary package to distribute, only the packed sources.

Please focus on the other issues and deliver as we did earlier.

**Comment by Ordojan** [comment]
Seems pretty clear. I'm going to close the issue. Okay?

**Comment by buep** [comment]
yep, research is done

**Comment by buep** [comment]
Please add a short section in the readme where we explain how we release and how the users can get the latest version.

**Comment by buep** [comment]
I'm including this in PAC jira release as we would like a the short description in the readme as explained above.

**Comment by buep** [comment]
@Ordojan - can you please finish up this task. It is easy ... just update the readme as we agreed upon.
