### ISSUE TITLE
research how to automatically make releases to github using the API

### ISSUE THREAD

**Issue by Ordojan** [Praqma/Praqmatic-Automated-Changelog#21]
I plan to store the releases on github. I want it to be a manual step in the jenkins pipeline. That means I need to know how to automate the process. 

documentation [here](https://help.github.com/articles/creating-releases/)

**Comment by buep** [comment]
What will the result of this issue be?

**Comment by buep** [comment]
What will the result of this issue be?

**Comment by buep** [comment]
This is not going to be part of the current PAC jira work package. The release is going to be done by tagging the version that is releases - just like we did earlier.
Issue #20 is including a short text about how we release and how the users find our releases. That is good enough for now.

Make this issue workable, but explaining exactly what it will include how the release will be done.
Then we consider it it a feature for later.

**Comment by buep** [comment]
Please groom

**Comment by buep** [comment]
Closing - we don't understand what it is... we get zip and tars native in Github based on tags.
I might have been relevant, if we one day pack PAC as binary, e.g. Windows installer.
But that will be part of that work.

**Comment by buep** [comment]
See #85 for creatinng PAC releasenotes on Github.
