### ISSUE TITLE
Git short SHAs is not supported

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#23]
Usually when working with Git one can use the short SHA to reference a commit.

PAC do not support that (old issue as far as I remember), so we should either support short SHA as expected or update the documentation for now and file a new issue on implementing it.

This issue was converted from Fogbugz case 13135 (Praqma's internal issue tracker) - case resolved there as Github issues is now official tracker for PAC.

**Comment by JKrag** [comment]
Is this still the case? Lets test.

**Comment by buep** [comment]
docker run --rm -v $(pwd):/data praqma/pac:snapshot -v from c789c7f --settings=/data/pac_settings.yml -c buep 'secret' jira

Gives me a changelog.

So closing this one.
