### ISSUE TITLE
There should be no HTML or like in markdown files

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#36]
PAC id report contains HTML, and obvious there is not need for using HTML instead of plain markdown.

```
#PAC id report

##1
 - fb493078: Test for multiple
 - cd32697c: Updated readme file again - third commit
 - a7b63f11: Revert "Updated readme file"

##2
 - fb493078: Test for multiple

##3
 - 881b321e: Updated readme file

##Unspecified
 - 55857d4e: Test for empty
 - a789b472: Test for none reference
 - f9a66ca6: Initial commit - added README

<div id="metadata-section">
  <h2 id="metadata-details-header">Details</h2>
  <div id='metadata'>
  <p>
    This changelog contains<strong> 7</strong> commits<br/>
    Number of referenced commits is <strong>5</strong> which is <strong>71.4%</strong> of all commits<br/>
    Which leaves out <strong>3</strong> commits without proper commit messages<br/>
    <span style='font-style:italic;font-size:small'>Changelog generated 2015-07-14 14:39:04 +0000</span>
  </p>
  </div>
</div>
```

Error report on SHA 8f88746a1204cd466dff1f636aa1f0f7406ccbb0

Used command:

docker run --entrypoint=/bin/sh --rm -v $(pwd):/data praqma/pac:snapshot -c rake test

**Comment by MadsNielsen** [comment]
I can't find anyplace in the code where 'metadata-section' exits? Did you edit the default template to include the html?

the default template for the id_report /templates/default_id_report.md does not incldue that part???

**Comment by buep** [comment]
Well if you read my issue you can see exactly how I created that report.

**Comment by MadsNielsen** [comment]
You'll have to show me. Running `docker run --entrypoint=/bin/sh --rm -v $(pwd):/data praqma/pac:snapshot -c rake test` from the PAC source repo root does not produce any finished changelog as output on my machine.

**Comment by buep** [comment]
Okay, I agree - sorry, it seems to be my mistake.

Command was used, but I couldn't see what it produced ... it was an old file I found.
