### ISSUE TITLE
PAC help must print version

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#44]
pac -h must print version number.

This means the release job of PAC must read the version.properties file and write a version.stamp.

The version.stamp file will contain one line:

$VER-$BUILD_NUMBER-$GITSHA

$VER comes from version.properties and $BUILDNUMBER from the jenkins release job and $GITSHA is the git sha being released.

TODO

* make PAC help command read the version.stamp and print it's content like:
```
Pragmatic changelog 
(Version: 2.0.0-1-46a45d6)
Usage:
  /usr/bin.....
```
* if no such version.stamp exists - the line read (Version: unknown)
* release job must delete (old one - the template) and write the version.stamp (file is not committed)
* version.stamp should exist in the repository and contain unknown

**Comment by MadsNielsen** [comment]
Couldn't quite get PAC to eat the parameters correctly. What it will do now is that it will read a version file called version.stamp and print that. When you run pac with no paramters or print the help.

**Comment by buep** [comment]
Created #45 as a suggestion we just discussed about reporting PAC version smart if using the script and not the container.

**Comment by buep** [comment]
I did a commit explained the versioning strategy.

**Comment by buep** [comment]
we must also remember to link to all the sub-files - from somewhere? or do we just put a readme in the docs folder?
