### ISSUE TITLE
Bug: Duplication of commit sha when task is mentioned multiple times in same commit

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#47]
When a task is mentioned multiple times in the same commit. SHA's are duplicated.

```
# PAC id report

## FAS-2 

### Summary

Riata was pronounced king in historic University of the

 - dfb4758
 - dfb4758 

## FAS-1 

### Summary

Thatcher's government since 1952). Scotland The Scots pine marten.

 - 3fc462e 
```

In this case the commit message was somthing like `FAS-2 and also seen in FAS-2`. We should make the commit list a `Set` instead of an `Array`.

**Comment by bicschneider** [comment]
This is also the issue if the two regular expressions harvest the same issue then it is also listed twice

**Comment by MadsNielsen** [comment]
@bicschneider Could you post a snippet of the result in this issue then? I've not seem that happen before. Tasks should be unique.

**Comment by buep** [comment]
@bicschneider @MadsNielsen if you see the same problem with two regexp harvesting the same issue twice, then make a new issue for it.
You can always reference this issue.

**Comment by buep** [comment]
Not relevant for PAC 2.0x - fixed. Closing.
