### ISSUE TITLE
Add debug to show json output

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#5]
With PAC 2.0, json datastructures are passed internally in the model, but the data are also used to reference in the template for the report.

Adding a debug switch, that outputs the json datastructues, makes it easy to see which data can be used in the template for the report. Very useful if you do not know all the returned data from e.g. Jira.

**Comment by praqma-thi** [comment]
I pushed some changes to a branch that would fix this.
It's untested though, as I lack a proper environment.
I suppose merging this in will have to wait for #18?

**Comment by buep** [comment]
That could be one option. But the our docker-pac container should actually work with PAC.

**Comment by buep** [comment]
Is this done ? there is a run time environment now that can be used. It is explained in the readme.

**Comment by MadsNielsen** [comment]
Yes this is done:

If you add the :debug: true flag in the task system...you'll get output of the returned 'data' from the task management system. Which you can use to help figure out the way to 'dot' through the output to get the data into your template

For example if you add the :debug: flag to the data in our Trac test...you'd get something like this in the console output:

```
[PAC] {:summary=>"Third ticket", :status=>"new", :description=>"Third ticket description"}
```

This can therefore be used to determine how the JSON of the tasks you're fetching looks like.






```

**Comment by buep** [comment]
Make sure to update docs as well - else you're not done :-)

**Comment by praqma-thi** [comment]
I can see my changes in the code, but it doesn't seem the branch was merged in.
Can we delete the branch, then?

I'll a note on the debug flag in the readme.
Anywhere else you'd like to see it?

**Comment by MadsNielsen** [comment]
@praqma-thi Yes you can delete your branch, i had to change it a bit to make it work in testing.

**Comment by praqma-thi** [comment]
Ah. There is a note of it in the docs. I'll just close this then.

**Comment by buep** [comment]
I only have two hits on "debug" if searching readme:

* the configuration file, but the configuration is not explained
* under "Noteworthy information"

Neither of them explain the nice point about implementing this flag - which according to this issue was:

"Adding a debug switch, that outputs the json datastructues, makes it easy to see which data can be used in the template for the report. Very useful if you do not know all the returned data from e.g. Jira."

So please explain this nice feature properly, maybe under separate section in the help about writing templates? That is where it belong I think - the debug flag can be used to the extra data available in the attributes which can be used in the template.

**Comment by MadsNielsen** [comment]
Started work on this on this branch: https://github.com/Praqma/Praqmatic-Automated-Changelog/commits/redo-documentation

**Comment by MadsNielsen** [comment]
This is already in code and works, it is also explained in the documentation how it works. I used it myself while copy pasting some of the responses from Jira while writing the documetation.

**Comment by buep** [comment]
Can you point me to the piece or text in the documentation where it is explained? I can't find it...

**Comment by MadsNielsen** [comment]
on the redo_documentation branch:

```
:debug: is optional set this to :debug: true if you want to print out the raw data returned for your task management system to console. Useful for figuring out how to dot your way into data in your templates. See The templating engine section for more information.
```

And then a bit later on i use it in the example on how to write a template for Jira
```
Writing a template for Jira

In order to best write a template for Jira we recommend that you try and run with the :debug: flag set to true on your first run. This should output a long list of json to console that Jira returns

Here is a snippet on how that could look like (this is taken from our automated tests):
```

That's the places i put it, if you feel i should be much more elaborate about please go ahead and add your say to it.

**Comment by buep** [comment]
Think we can resolve this as issue #7 should mention under usage section - I added this comment to #7: https://github.com/Praqma/Praqmatic-Automated-Changelog/issues/7#issuecomment-215444967
