### ISSUE TITLE
The 'none'  task system always returns false when it is applies

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#50]
When the none task system is applied... 

```
[PAC] Applying task system none
[PAC] Applying task system jira
[PAC] Ignoring encountered errors. Strict mode is disabled.
``` 

It is a false negative. when apply is applied to none we should return true since...when the task system none is applied...nothing happens.

**Comment by MadsNielsen** [comment]
This was fixed in https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/065a13078e8dd937fae9fcbba1a47ff8cbff24f5 

I've not been able to reproduce it since.

**Comment by buep** [comment]
ok
