### ISSUE TITLE
Support multi-request data gathering

### ISSUE THREAD

**Issue by JKrag** [Praqma/Praqmatic-Automated-Changelog#54]
Short version:

When getting data from JIRA, there are certain fields (like links to commits) that are only accessible via a second API call using the issueId returned from the first call.

I don't know yet how this should be implemented, but it would be cool to support getting this data via a second request and adding result to the data hash map available for the templates.

The example I have come across, that we are trying to solve, is creating a release note that actually has links to bitbucket for the commits referenced. If a JIRA issue has links to commits (as shown in the JIRA issue UI), then it is possible to get information about these, including the actual URL to bitbucket, by requesting from a developer api endpoint:

```http://<JIRA SERVER>:8080/rest/dev-status/latest/issue/detail?issueId=10915&applicationType=stash&dataType=repository```

Where the issue ID was taken from the initial call to : 

```http://<JIRA SERVER>:8080/rest/api/latest/issue/ABC-23```
 
We have just started this journey, so I assume that we will come across other cases where it is relevant to extract further info via subsequent api calls. Of the top of my head, I could see it very relevant to be able to extract basic info about linked issues or the story/epic that a "task" belongs to, and include this in the release note.

**Comment by buep** [comment]
Addition to your idea, which might be a good use-case, is to add support for a number of extra extractions round specified by some kind of configuration.

The requirements are that data from the first extraction phase are iterated, and that you construct the query as for the first round.
Just a quick though...

**Comment by MadsNielsen** [comment]
An easy thing to to do would be the ability to daisy chain requests. That is a way to store return values from each request into variables, and then use the variable in the next request.

for example: 
```
:query_string: 
 - { url: http://<JIRA SERVER>:8080/rest/dev-status/latest/issue/detail?issueId=10915&applicationType=stash&dataType=repository, extraction: 'jira_basic' } 
- { http://<JIRA SERVER>:8080/rest/api/latest/issue/jira_basic['url'] extraction; 'jira_final' }
```
Then it would be a simple matter of merging {1} and {2} in the final variable for the template, the extra data could get it's own key in the resulting Ruby hash i.e extra data from 'jira_fina' would be exposed in `data.attributes.jira_final` 

Just throwing the idea in here.

**Comment by JKrag** [comment]
Discussion with Mads.
We sketched out the following as a potential conceptual "syntax".

Allow specifying multiple rest calls. For each we contribute to the global dataset, optionally (usually) namespaced in a sub-map. The first call would typically go to the "global" properties.data map.

Variable expansion should allow dotting into collected data from previous steps.

It is our impression that this solution should get us a very long way in supporting many use cases, even calling to other systems etc.


```
    :name: jira
      - { pattern: '/(PRJ-\d+)/i', label: jira }      
    :steps:
      - 
        :query: "http://your.server.hostname/rest/api/latest/issue/#{task_id}"
        :usr: "user"  
        :pw: "password"
        :regex:
        :namespace: 
      - 
        :query: http://<JIRA SERVER>:8080/rest/dev-status/latest/issue/detail?issueId=#{properties.data.issue.id}&applicationType=stash&dataType=repository
        :usr: "user"  
        :pw: "password"
        :namespace: issuedetails
      - 
        :query: http://<REQUIREMENTSSERVER>:4242/rest/fisk?reqId=#{properties.issuedetails.RID}
        :usr: "otheruser"  
        :pw: "otherpassword"
        :namespace: req_details
```

**Comment by buep** [comment]
Great inputs. I like we start with looking at how it would be used :-)

Could the namespace be mandatory? I don't like the implicit assumption that if empty it is something special... either mandatory or omitted

How is iterations handled? In the first query we get a list of task_id's, and in the second entry we use these. It iteration handled automatically by implicit assumption that we always iterate over something or how?

Your example is for Jira, what is using Trac? Then the returned data isn't json, so how will that work?
The configuration file needs to handle both situation I think.

What modules in PAC or where do you architectural think this functionality belongs?

**Comment by JKrag** [comment]
We hadn't even thought about iterations in this context, but I agree that it might be very relevant and a useful feature to have. I will start thinking about a good "UI" for this, and see what surfaces. 

@buep Can you expand on your idea of implicitly assuming iteration?

----------

One superficial thought, that I already had, was to allow some sort of "user scriptlet" support. I.e. a easy way for the user to provide some extension logic. This could be at the ruby level, or through some dsl-type syntax (maybe Yaml is enough if we think a bit).  

My thought was that anything beyond whatever we decide to be internally supported, could be optionally "scriptet" by the users. Extracting collections of data and doing multiple api requests while iterating over them, might easily fall in this category :-D 

I think we should initially try to focus on the simple use case where we extract simple values, and make single calls based on these, more or less as conceptually described in the previous comment, unless we can come up with a well-defined intuitive way of treating everything as a collection (of maybe 1 value).

**Comment by buep** [comment]
If you hadn't thought about iterations, how would the following then work?

query: http://<JIRA SERVER>:8080/rest/dev-status/latest/issue/detail?issueId=#{properties.data.issue.id}
... I assume returns a list? The properties.data.issue.id which is build by the first query?

I imagine you would implement by always iterating over doing a query for each item in properties.data.issue.id list? Then it doesn't matter if it is a list with one element or not.

I think we need more work on this. I like your "plugin" approach, especially if it would be YAML or Liquied (that we already have).


What about support for those queries that do not return json? Would you convert them to json or what?

**Comment by JKrag** [comment]
@buep The initial call to jira uses a issue "name" like PRJ-123. It returns a complex json structure with lots of data. One of the data fields is a single numeric "issueID", presumably an internal key for the actual issue.
This is the issue id that has to be extracted and used to query the issue/detail? endpoint. So as far as I can see, there is no iteration involved in this specific example.

**Comment by buep** [comment]
So you only run the second query for one issue then?

**Comment by JKrag** [comment]
No, I want to run the second query for each task, just like the first query. The only difference is that the second query needs an identifier returned from the first query, i.e. not present in the commit message. 

I thought you were (initially) asking about the case where the first query returns a collection of items, and pac should "fan out" and request additional data for each item. This would also be a cool and useful feature, but is not the one I am initially targeting here.

**Comment by buep** [comment]
Okay, now I get it.... we might need a workflow diagram or some very well thought documentation for the user around how this work.

Have you considered performance for this? We might need to have attention on that. Maybe re-use threads for something for similar requests. Also make sure not to DDOS the task system from the build servers is many is doing changelogs.

Doc tips for workflow could be something like this: https://github.com/Praqma/automated-branch-pipelines/tree/master/docs/sequencediagrams


One last thing still reside to be clarified - what about Trac (on possible other systems) not returning json? How will this be handled?

**Comment by MadsNielsen** [comment]
@buep Regarding Trac, i think we might want to limit the scope of the intial implementation to only be usable for the 'rest' task system (We talked about how the Jira tasks sytem in reality is a rest tasks system, since you can also use the same system with Github issues). That is very doable with current architecture.

**Comment by buep** [comment]
Okay, but do this mean we need to fix the other issue first making a rest-task system instead of a specific jira task system?

Further, how do you imagine to explain these differences in documentation? Support different configuration for only certain task systems? It needs to be pretty clear what is supported for what.

I don't want Trac to limit functionality in other use-cases, but certain I do not either want a very complex documentation with something being available now and then depending on a lot of things.

Any good way of structuring this?

Can non-rest task systems be supported later? How do you imagine to convert to rest or support them?

**Comment by MadsNielsen** [comment]
@buep It would make sense to do the 'renaming' to rest first. It's not a large task, and we should still be backwards compatible even though the system name is `:jira:` in the configuration. Jan did the conversion easily, so i do not see that as a large task that cannot be done before this one is started. 

In regards to documenation, we can simply state that for `:rest:` or `;jira:`  if there is a `:steps:` section this could potentially be a multi-request operation, this should retain backwards compatibility of configuration files. So it's `:query_string: || :steps: [1...n] query_string(s)`  
 
For non-generic task systems, that use their own specific API's, if they use non-standard ways of communicating and return data in, we'll need to create drivers (in ruby) that support them via configuration, theres is no simple solution to that issue as far as i see it. To make that possible we'll need to implement something a'la what @JKrag suggested in #58.

**Comment by buep** [comment]
So make sure to think about architecture. I don't think it is a good idea to support multi-request in one way for json system, and in another way (plugin ish) for other systems like Trac.
Could we consider support the parsing to json righ away from the task module? So Trac would convert to json if it do not get json?

I'm okay with we implement support to start with for json, but I want a firm plan on how I could be implemted for Trac, so we can make sure design are okay and we don't need a big refactor later to support Trac.

**Comment by MadsNielsen** [comment]
@buep Sure. In fact the part that adds additonal information to a task and parses JSON is already in a seperate module where i'm proxying the JSON parser (Decorator). So i think most of your concers are covered in the code. 

It's also one of those things where we probably will learn alot of what we can do, and cannot do during implementation, so if this feature is kept at a maximum of 1-2 days of work for the rest part, including test, then the refactor, if needed will not be expensive once we figure out how and wheather we need it for non-resty systems.

**Comment by buep** [comment]
Okay.

Then estimate this issue. Make sure to have time also, beside the usual stuff, to write an implementation proposal with design details, and refactoring suggestions, if one was later to support non rest systems.

You can estimate based on we solve 58 first, about making generic json instead of specific jira.

**Comment by buep** [comment]
Please create new elaborate and specific issues, groom them so I can close this briefing and prioritize the specific issues.
Link to this issue.

This is issue probably have important knowledge to be documented in docs when implementing. Be aware of that.

**Comment by JKrag** [comment]
Extracted #69 for the part about refactoring/renaming to generic rest.

Extracted #70 for the part about refactoring to support multiple request steps. This is work in progress in PR #68 (code done, test and docs not yet)

**Comment by JKrag** [comment]
Regarding @buep's comment on June 6th about how to support this in non-rest task systems. I really like the idea of leaving it to the task system plugin (e.g. Trac) to do the conversion to json.

Or rather, I would probably not choose json as the generic result format, but rather have all plugins, incl. the rest ones, deliver a ruby map, as this is what we need anyway. I see no reason to convert to json first when we parse this into a map anyway. 
@MadsNielsen Comments?

**Comment by buep** [comment]
> Regarding @buep's comment on June 6th about how to support this in non-rest task systems. I really like the idea of leaving it to the task system plugin (e.g. Trac) to do the conversion to JSON.
> Or rather, I would probably not choose JSON as the generic result format, but rather have all plugins, incl. the rest ones, deliver a ruby map, as this is what we need anyway. I see no reason to convert to JSON first when we parse this into a map anyway. 

Yes, that is a good suggestion. Can you make sure that idea is moved to #70 which I guess is now where the actual work is to be done?
In addition I will need a drawing extending the current drawing that shows which objects, maps etc. are passed around in the system. E.g. use draw.io so we can include the export in this repo.

After that I guess this briefing can be closed? Are there anything else left?

> Extracted #69 for the part about refactoring/renaming to generic rest.

OK

> Extracted #70 for the part about refactoring to support multiple request steps. This is work in progress in PR #68 (code done, test and docs not yet)

PR 68# closed, please work from issue #70 instead and use our normal workflow.

**Comment by buep** [comment]
@JKrag - I final question to your first entry in this issue where you explain the use-case.

Why do you want to take the commits from the jira issue instead of git, which are the truth? Will there be references to other git commits on the issue that are not part of the repo being generated changelog from?

**Comment by JKrag** [comment]
@buep The simple answer is that it is not as such the list of commits I am after, but the fully formatted deep links into Bitbucket server that I can't generate myself in a stable manner without a guaranteed knowledge of which bitbucket repo each referenced commit belongs to. Jira displays these links on the issue, but the only way to request them is through an extended api that can only be queried with an internal id gained from the initial request.

**Comment by buep** [comment]
> @buep The simple answer is that it is not as such the list of commits I am after, but the fully formatted deep links into Bitbucket server that I can't generate myself in a stable manner without a guaranteed knowledge of which bitbucket repo each referenced commit belongs to. Jira displays these links on the issue, but the only way to request them is through an extended api that can only be queried with an internal id gained from the initial request.

OK, good example then. It is because you need information you can't deduce from your context within the repo itself.

**Comment by buep** [comment]
Grooming meeting today, we agreed that this issue is replaced by #70, which again is replaced by the improved design idea in #71 so I'm closing it.
