### ISSUE TITLE
Describe and document the datamodel and flow (case 14167)

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#6]
With reference to the architecture https://github.com/Praqma/Praqmatic-Automated-Changelog/blob/master/docs/designview.png please describe the data model or object for each core parts and the flow for parsing it around.

How do it look to start with, what is added where, how it the flow. Describe the json structure. 

Describe the reasoning behind the choices of the datastructure.

**Comment by lakruzz** [comment]
@MadsNielsen This might be closed - if not specify what's missing

**Comment by lakruzz** [comment]
related to #16

**Comment by buep** [comment]
I have added comments to the commit, think it need a bit more work.

Especially related to the datastructures that are passed around. They are very interesting to document - that was the original goal of this issue.

But all in all a good improvement of our docs.

**Comment by MadsNielsen** [comment]
I added a bit of snippets of code to the datamodel. For now i will close this as 'good enough'. I've got plenty of comments in code to the pieces that need explanation so that should be enough.

**Comment by buep** [comment]
Added a few comments in the last commit - you might want to look at those.

Further your comment:
> I've got plenty of comments in code to the pieces that need explanation so that should be enough. 

Not sure what you mean by this? There is lots of things in the code that is really not explained. I would recommend to use some kind of ruby doc (like javadoc) in the future, that would have been way easier than adding snippets of code to the documentation.

Examples:

task.rb:
```
#This is the Jira task system (EXAMPLE ~ NOT FINISHED)
  class JiraTaskSystem < TaskSystem
    def initialize(settings)	
      super(settings) 
    end
```
? why not finished?

report.rb:
```
class Generator
	  #This one has become a tad too specific for git. We get the short shar (first 8 digits). And
	  #we trim the subject (That is the first element in the list when splitting the message on a newline. 
	  #Takes a 'PACCommitCollection' as an argument  
	  def generate(tasks, commits, templates)
	    templates.each do |t|        
```
? comment says takes a PACCommitCollection, but the method takes a list of tasks, commits and templates ???


model.rb
```
module Model

	#Model object representing a discovered task
  class PACTask
    def initialize(task_id = nil)
      @task_id = task_id      
      @commit_collection = PACCommitCollection.new 
      @attributes = { }
      @applies_to = Set.new      
      @label = Set.new
    end
```
??? attributes not explained



I still don't think the flow between the model objects are very well explained. Image you would pretty print the lists in the different part of our model, when passing them from one module to another - that is the kind of overview I was asking for.

Examples - imagine you pretty printed them:

How would the commit_map for example look here: https://github.com/Praqma/Praqmatic-Automated-Changelog/blob/master/pac.rb#L68

How would the tasks list look here: https://github.com/Praqma/Praqmatic-Automated-Changelog/blob/master/pac.rb#L71

And the populated task list here: https://github.com/Praqma/Praqmatic-Automated-Changelog/blob/master/pac.rb#L77

**Comment by buep** [comment]
OK
