### ISSUE TITLE
Allow user to specify password and username when running pac via command line (case 15129)

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#63]
We need to implement this feature if we want to be able to have the automation of changelog be a part of a pipeline. 

This is because we do not want to store passwords in cleartext in public repositories. In order to allow it to be used as part of our development proces we need this. This allows us to add a project specific configuration file and template to each project that want's to generate a changelog from PAC. 

Since we support multiple types of systems...we should allow something that allow you to set password and username to specific task system. 

So we have username, password and task system target. 

Like so -c <username> <password> <target>. This can be repeated N times for each system you wish to override credentials for.

**Comment by buep** [comment]
CLI ? We don't have any command line interface in PAC. Please next time describe so I don't need to read the code contribution to understand what the issue is about.

Second, what is this file you added?  pac_settings.yml 

Third - why is template changed as part of supporting a new command line parameter?

**Comment by buep** [comment]
And you still can't work on issues that are not workable - see http://www.praqma.com/stories/a-pragmatic-workflow/

**Comment by buep** [comment]
And I'm missing tests

**Comment by MadsNielsen** [comment]
Current solution allows you to do like so:

`-c my_user my_password jira -c my_other_user my_other_password  fogbugz`

Basically <username> <password> <target> (Since we can have multiple task systems.

There's a small test, where i've converted the docopt hash values and passing them into the mecanism that sets the settings for PAC.

**Comment by buep** [comment]
Have you tested the options and that they parse to the same as if I was using a configuration file?
And if it works from the configuration file as well?

Also updated all docs accordingly?

In your configuration file, is the options called usr and pw? Then here there are without that mention? Is that by purpose or accident?

**Comment by buep** [comment]
I added comment to your commits referencing this case - please check and fix inline comment on the commits.

**Comment by buep** [comment]
Also check comments here: https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/065a13078e8dd937fae9fcbba1a47ff8cbff24f5

Need fixed.

**Comment by MadsNielsen** [comment]
This will be fixed with when the branch https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/feature/pipeline-autogenerate is merged. 

We've removed the rake command and are using the -c flags to connect to Github. We do not specify password and username in the config file. So if that works, the job itself is a self-test to verify the correct behaviour. There is already a simple semantic te

**Comment by buep** [comment]
Please make sure jobs are never deleted if renamed... one of my comments on the commit mentioned above.
Please go over them also... see if everything is handled :-)

**Comment by MadsNielsen** [comment]
@buep the jobs are not deleted. They're still in the view, just disabled? I've set job-dsl to 'disable' renamed jobs.

**Comment by MadsNielsen** [comment]
@buep I've talked with @praqma-thi that we'll skip using numbers in our job dsl scripts from now on. Order should not be part of the name, we won't ever need to rename and jobs by doing that, let's introduce that convention. As to avoid that job dsl being configured to delete stuff, the cheapest way is probably to have a proper backup instead of trying to script/modify the job dsl proces.

**Comment by buep** [comment]
>  we won't ever need to rename and jobs by doing that, let's introduce that convention

Not sure I believe in that, risk is to high I think.

> cheapest way is probably to have a proper backup instead of trying to script/modify the job dsl proces.

Not working either, if someone runs the new jobs as well... you have two sets of jobs with important information. You can't merge them.

So I still don't the problem is solved in general, that was what I wanted an issue on in another context than PAC.... how we handle such risk using job dsl.

We can take the discussions there - write me an issue somewhere.

**Comment by buep** [comment]
Is this issue about specify password and username revolved then?

**Comment by MadsNielsen** [comment]
I believe it is. With commit https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/94d16f5c6bc85291a5040a369242757712d4ff58 i've updated the missing documentation. There already is a small unit test, and we've already generated a report using these options in our pipeline.

**Comment by buep** [comment]
Roger, then we close.
