### ISSUE TITLE
Pipeline should generate it's own report (case 15125)

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#64]
Currently the pipeline for PAC does not generate it's own chagelog. We need to fix that. 

This can be done with the `jira` task system since since GitHub supports basic auth, with username and an autogenrated tooken as password. 

One issue though how do we store access tokens (PW/USRNAME)? I do not want to read from a file (volatile), and we cannot put our passwords in the job dsl that creates the pipeline since the pipeline is public.

**Comment by MadsNielsen** [comment]
Right what needs to be done for this to be groomed? We want to do this because it's the best self test there is for our own product, that it creates it's own changelog, as part of our build pipeline. It's already more or less working in the current pipeline except i want to move it all to a rake task, where the user can provide his own credentials to generate the changelog.

**Comment by buep** [comment]
> except i want to move it all to a rake task, where the user can provide his own credentials to generate the changelog
- what does this mean? The job should not take any parameters, it should be a fully automated part of our pipeline.

Further:

* what version of PAC will you use to generate the changelog in the pipeline jobs?
* what are "period" for the change log? since last release or?

**Comment by buep** [comment]
How will you "publish" the report?

**Comment by MadsNielsen** [comment]
Great questions. Let me try to elaborate and see if i can answer them

Question about parameters: Our job DSL is public, so i do not want to put my private user token (password) inside our job dsl scripts or config files. That means that i need some means to pass this password to PAC for the changelog to be created. Rake has support for this like: rake <task>[params..]. This enables us pass in parameters with the Credentials Build parameter, avoiding having to store secrets on a slave/file or anywhere else, we can simply use the Credentials mechanism of Jenkins.

What version of PAC? Ideally i'd want to build a totally new image from the sha of the repo, as in the git commit that triggered..this can be easilly done with rake as well. You could capture the short-sha and create a snapshot pac/praqma:<sha> or something similar and create the changelog with that image. When done delete the image

Period: Latest tag, of any name. We only tag on release, so this is good enough.

Publication: We could create a HTML file, and publish it with the HTML publisher. We can later decide to include the real report when it's been made pretty.

**Comment by buep** [comment]
> Question about parameters: Our job DSL is public, so i do not want to put my private user token (password) inside our job dsl scripts or config files. That means that i need some means to pass this password to PAC for the changelog to be created. Rake has support for this like: rake [params..]. This enables us pass in parameters with the Credentials Build parameter, avoiding having to store secrets on a slave/file or anywhere else, we can simply use the Credentials mechanism of Jenkins.

Suggest this solution instead:
* create a praqma pac changelog user on our github (make sure it have only read permissions), use that user to authenticate. give it access to only specific repository (PAC) and make sure to follow ournaming conventions (thinks it is Praqma-something, check our users)
* use the Jenkins inject secrets plugin, type in the auth. token in the job for the new user
* the plugin will mask the password is you check that in the configuraiton thus it will never show in the console anywhere

You can pass it on command line in the latest version as far as I remember....

> Period: Latest tag, of any name. We only tag on release, so this is good enough.

* fine :-)

> Publication: We could create a HTML file, and publish it with the HTML publisher. We can later decide to include the real report when it's been made pretty. 

Okay, let's do that. Also archive latest md and pdf file on the build, remember to discard archived files on old builds (say older than 10 builds or something)

> What version of PAC? Ideally i'd want to build a totally new image from the sha of the repo, as in the git commit that triggered..this can be easilly done with rake as well. You could capture the short-sha and create a snapshot pac/praqma: or something similar and create the changelog with that image. When done delete the image

I think gave some github commit comments on one of your recent commits around this. 
I don't see why we should involve rake?
Why just not run "docker build . " (you have the build file in repo) and then run the command for pac that uses docker to generate the report?
That is simpler, because you get a latest pac docker image, that have the latest coce :-)

**Comment by MadsNielsen** [comment]
@buep Thanks. Those are sensible suggestions. Let's roll with that then.

**Comment by buep** [comment]
Cool, ready to work then :-)

**Comment by MadsNielsen** [comment]
Hi @buep i took a quick look at the API for Github. It's not possible to create a token for a single repo. It seems that you can only create a global read-all repos public key for a user. 

I guess that is okay? We still have to expose the user and the token key in the job dsl which is public, are you okay with that?

**Comment by buep** [comment]
But that isn't really a problem, if you just add the PAC changelog user to only the PAC repository, and not our organisation.

You don't have to expose the token in job dsl, you can expose on the Jenkins hashed version. Create a UI job, check the config.xml and take the token from there. Or use one of the secrets plugins.

**Comment by buep** [comment]
please make sure I and other review your changes before you push them to master.... maybe a first review with a "dummy" token so we can see it the concept first.

**Comment by MadsNielsen** [comment]
Together with https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/ef10e57f0fd8e4f86981ac99cc7ad57e09e21216 we can now generate a report. We don't even need to mention the token at all, we can just require a global variable be set with the token contained. The password is masked when the job runs with current solution. Users who wish to run the same set of job as us, can copy the pipeline and maybe choose a different way to inject user and password.

**Comment by buep** [comment]
Checked your commit, seems like a fine solution with the releasePraqma and the token from credentials. Security wise it is as long as it is only ourselves that can configure jobs and copy jobs, so you cant re-use our jobs to create new ones that does something different. Our Jenkins server should already be configured this way.

One thing though... you might consider that the name "pac_token" is that obvious regarding where it is used whn you look at our global jenkins configuration... consider if a better name will explain better what it is used for. Long names are okay.

**Comment by buep** [comment]
Beside that I'm good with this now

**Comment by MadsNielsen** [comment]
Right @buep i've renamed the jobs, so that we have all the build history, so old history is restored.

**Comment by MadsNielsen** [comment]
Right. PAC now generates it's own report. Job-dsl is updated and functional tests are running again.

**Comment by MadsNielsen** [comment]
@buep Right i think this one is done. we've generated a pipeline from the dsl and i've created and i've re-enabled the seed job to use the pipeline groovy script.

**Comment by buep** [comment]
ok
