### ISSUE TITLE
When no value for tag name given in latest tag. Default to newest tag of any name

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#65]
Often when you work, you normally only tag releases. Since PAC was designed to be run whenever there is a new commit on a branch (HEAD) on integration, it would be convenient if you didn't have to memorize the name of the tag. 

So when running pac you could just do: 

`pac from-latest-tag --settings=/home/myuser/mysettings.yml`

This would also work well in cases where the tag names do not share any common names and it's hard to come up with a pattern that matches them.

**Comment by buep** [comment]
Please elaborate this issue so others can agree or disagree....

**Comment by MadsNielsen** [comment]
This issue is not something im going to implement. The current implementation allows you to just use "*", That will match any tag and use the lates. So this is closed with "Will not implement"

**Comment by buep** [comment]
You cant propose a change, then do some commits and then say you won't implement it.

So what was actually done? (without I need to look at the commits please....)


How can I use * ? What does the help text say? Please explain to me - I'm not sure "*" is a good character to use...

**Comment by ReleasePraqma** [comment]
Damn i missed the commit on this issue. I'm going to revert that change. 

The reason it wont work is that when you use postitional argument it expects a value immediately after. So it's never going to work with no-args using docopt.

We can't change the "*" though, Ruby uses the git glob-syntax shenanigans with * as wildcard. I don't want to wrap that into something that allows to specify something non-globish.

**Comment by buep** [comment]
How will the command look like then? can you give some example so I can see how it works with asterisk ?
Not sure it is a safe char on command line for e.g. linux... please elaborate

**Comment by MadsNielsen** [comment]
Like so: `docker run --rm -v $(pwd):/data praqma/pac:snapshot from-latest-tag "*"`

**Comment by buep** [comment]
Okay for that command, still don't think asterisk is a good choice, but it works also on Jenkins and in execute shell steps so that is okay for now.

Make sure documentation is updated...

**Comment by MadsNielsen** [comment]
Added a couple of changes on this branch: https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/feature/asterixed-any
