### ISSUE TITLE
Refresh Jira evaluation license in our test jira instance (case 15023)

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#67]
We haven't automated this, so need to do it once more to get a working jira test instance. See last time we did it - #59

**Comment by buep** [comment]
See also #35 about the general problem, we haven't solved yet.

**Comment by MadsNielsen** [comment]
This was closed in https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/51aaa5285feb6e40f8b874c447ece88e9012e048

Typo in commit msg?

**Comment by buep** [comment]
Should be, I used our default workflows and aliases.

Never the mind is wasn't closed fully because the pipeline didn't verify the commit. Not it is passed.
