### ISSUE TITLE
Documentation is needed for PAC 2.0 (case 14173)

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#7]
Thing to describe and document in the user documentation:

- more labels can be assigned to the same commit, if re-using regexp
- the order of regexp if you expect more hits?
- what is labels used for?

Explain how PAC extract task list and how to create template for it.

**Comment by buep** [comment]
I can't review this pr git commit diffs, I will look at is as soon as we have master branch with all changes.

**Comment by buep** [comment]
we need a new feature list a least.

**Comment by buep** [comment]
Comments on the documentation - needs to be fixed.

I asked for an explanation of what I should use labels for? The following text from current readme do not explain the use-case:
> The settings file has the list of regular expression, each pattern has one label property. When a regular expression is matched, the label from the matched commit is applied to the task the commit belongs to. Each task can contain multiple labels, a good example would be to scan for commits with a task reference that has the words "Wont fix" and apply the label wont_fix to those matched commits.

I can't find anything about assigning more labels to same tasks - I asked for that as well.
You need to explain why I would do it, and how to do it (examples):
> more labels can be assigned to the same commit, if re-using regexp

I also asked to explain
> the order of regexp if you expect more hits?

Could find any user explanation on that either. Few notes in developer information which makes me understand it... but explain it to the user instead.

**Comment by MadsNielsen** [comment]
https://github.com/Praqma/Praqmatic-Automated-Changelog/commits/redo-documentation

**Comment by MadsNielsen** [comment]
@buep  and @praqma-thi Can you review the Readme file...i need to know if my writing is totally off the bar and makes sense.

**Comment by buep** [comment]
I will do that...

**Comment by buep** [comment]
I will contribute with some things.... and try to see if understand what we talked about yesterday.

I will also move development information out the the primary readme.

Using your branch.

**Comment by buep** [comment]
I will contribute with some things.... and try to see if understand what we talked about yesterday.

I will also move development information out the the primary readme.

Using your branch.

**Comment by buep** [comment]
I need to remember to mention the migration guide in the repo readme...

**Comment by buep** [comment]
we should not forgeta release section, similar to: https://hub.docker.com/r/praqma/pac/

Hopefully replacing the one above, so I can just reference that in our readme.

**Comment by buep** [comment]
Remember to mention "debug" feature under usage, see #5

**Comment by buep** [comment]
we must also remember to link to all the sub-files - from somewhere? or do we just put a readme in the docs folder?

**Comment by buep** [comment]
I simplified few of the sections from less implementation-details oriented to more user-friendly (that is probably also developers) writing - I hope.

Check the commits I made for diffs.

Hope you can continue it from here again, I didn't have as much time as expected to go through it all.

**Comment by buep** [comment]
I'm working on this today... need to finish this up.

**Comment by buep** [comment]
I'm done - all documented restructured, cleaned and elaborated.

I only need information from you @MadsNielsen on the following FIXME:

./docs/templates.md:* `title` Title of the report - from the configuration file. FIXME - is title working?
./docs/configuration.md:You can specify a boolean **`pdf: true`** only together with HTML templates and HTML output. See FIXME (needs to be explained, is html template required?)
./docs/configuration.md: * **`label`** (_required_ FIXME is label required?) is used to group the results, and be used for selecting, grouping and iteration in the templates. See [How to use labels](label_configuration.md)
./docs/configuration.md:* **`trac_usr`** is the Trac user ID, and the user must have `XML_RPC` permissions FIXME
./docs/configuration.md:_TRAC server needs configuration FIXME_
./docs/using_the_pac_docker_image.md:The relevant PAC configuration file matching the above needs templates defined as follows: FIXME
./docs/using_the_pac_docker_image.md:FIXME Make sure that your configuration file points to the location of the mounted templates as seen from the container, in this case `/pac-templates/[your-template]`.

They are probably easy to fix, some are just questions, some might just because I don't know.

@MadsNielsen - can you fix the last FIXMEs above and assign back to me?
I will finally deliver and resolve this issue.

**Comment by buep** [comment]
I pushed Mads' changed and the complete redo-documentation branch as ready/7-documentation-needed-for-pac-20 ... it passed the pipeline and documentation is now nice :-)

Finally!

**Comment by buep** [comment]
@MadsNielsen can you look at the test failure? http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Praqmatic-Automated-Changelog%20pipeline/job/2_functional_test_pac/43/console

**Comment by buep** [comment]
Tests running now, false negative due to some docker issues.
