### ISSUE TITLE
Support multiple requests for each task system

### ISSUE THREAD

**Issue by JKrag** [Praqma/Praqmatic-Automated-Changelog#70]
This relates to the long grooming discussion on #54 and is a subtask for implementing that work.

This issue should include the following change:

instead of specifying one query_string, usr and pw set for a certain task_system section, we want to specify a list of steps, where each step allows a request agains a specified query_string with a usr & pw.

I.e. instead of:

```
:task_systems:
  -
    :name: jira
    :query_string: "http://your.server.hostname/rest/api/latest/issue/#{task_id}"
    :usr: "user"  
    :pw: "password"
    :regex:
    - { pattern: '/(PRJ-\d+)/i', label: jira }  
```

we want to specify something like:

```
 :name: jira
    :steps:
      - 
        :query: "https://api.github.com/repos/Praqma/Praqmatic-Automated-Changelog/issues/#{task_id}"
        :usr: 
        :pw:
        :namespace: github
```

where the results from a specific query can optionally be namespaced in the resulting data map that is passed on to the template engine.

**Comment by JKrag** [comment]
There is also the question of how we handle "backwards compatibility". I see two main options:

1. support both the `steps`syntax and the old "single request" syntax.
2. Don't be backwards compatible, but document the trivially easy migration.


Currently, I have a slight preference for solution 2. This keeps it simpler in the long run, and there is no real value in supporting old config formats.

Either way, I see no reason to have to create a sub issue for this alone.

**Comment by buep** [comment]
I'm okay with 2 - we just bump major version.

I changed title slightly, as this is more a feature than a refactor.

I need this issue groomed, as I think it is kind of big and includes several tasks which should be done in the following order:

* change all example configuration files and documentation to match the above change
* describe the use-case in the docs, explaining what can be done with this feature and why it is interesting (see @JKrag example in #54)
* update tests
* write new tests
* finally implement the code

**Comment by JKrag** [comment]
My original plan with this issue was for it to specifically be a sub-task of the bigger story, involving only the refactor to change the syntax to a list under "steps" in such a way that rewriting the yaml file as shown above, but with a lank namespace, should yield exactly the same end-result as previous versions.

The fact that it thus implicitly also now already supports multiple steps is more a biproduct of a correct implementation of the above.

Replacing #54 with a new issue #70 that also includes the entire "epic", that we then have to break down, seems a bit pointless.

With regards to grooming, I think you already did a nice job. If you want, we can split your bullet list into separate issues, but I think that might be over administration.

**Comment by buep** [comment]
> With regards to grooming, I think you already did a nice job. If you want, we can split your bullet list into separate issues, but I think that might be over administration. 

Fine as long as there are no tasks with bigger estimate than a days work (I don't think it is).

> Replacing #54 with a new issue #70 that also includes the entire "epic", that we then have to break down, seems a bit pointless.

OK, can you create issues linked #54 on the rest of the work then so we can close #54 which is a breifing.

**Comment by buep** [comment]
I don't get the difference between #54 and #70, as I can't figure out which part of #54 is missing...

**Comment by MadsNielsen** [comment]
Test focus:
 - Configuration parser
- Input/Output. GIven raw response data, make sure that data is in the correct namespace on task.

**Comment by JKrag** [comment]
This issue is now superseded by the improved design covered in #71

**Comment by buep** [comment]
And we agreed to close this.
