### ISSUE TITLE
Pointing to a non-existing settings file invalidates logging

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#87]
Running this command

```
mads@mads-VirtualBox:~/github$ ruby ./Praqmatic-Automated-Changelog/pac.rb from "44343434" --settings=pac_settings.yml
``` 

This command runs pac from outside current working directory, all errors are silently ignored. This is because the logging framework fails to intialize properly. The above example should say that the settings file doesn't exists, it doesnt do that atm. 

Resolution:

- Implement test that fails with current implementation
- Fix implmentation, see that test does not fail.

**Comment by buep** [comment]
Needs an estimate and priority.... and is it done?

**Comment by MadsNielsen** [comment]
I had half hour free so i cooked up this: https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/87-fix-for-logger

I'm still thinking we're intializing too much at once in the method that parses the settings file. Have half an hour left to ponder how we might solve that... :)

**Comment by buep** [comment]
Okay but we still don't work on anything we don't agree on... we just don't randomly go around and hack on our projects.
