### ISSUE TITLE
Missing exception when settings file does not exists

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#88]
Resolution:

- Write test that fails with current implementation
- Fix implmentation

**Comment by buep** [comment]
Needs an estimate and priority.... and is it done?

**Comment by MadsNielsen** [comment]
This is more or less done: https://github.com/Praqma/Praqmatic-Automated-Changelog/commit/d0e31cbd84a4b7aa4f23a1e463d80fd1a9117ffb

I just need a second set of eyes to look at the code before it can be merged.

**Comment by buep** [comment]
See my other comment... we follow our workflows and not just hacking around.

Anyway, get someones second pair of eys on it and finish it up.. and minimize work in progress.

**Comment by MadsNielsen** [comment]
Right. I'll see if @JKrag has any comments on my change.

**Comment by buep** [comment]
minimize work in progress - is this done? It was a small one.
