### ISSUE TITLE
Suggestion: Migrate tests to RSpec

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#92]
I looked at our current tests for PAC and it seems that there is a distinct lack of feedback when you run the tests. The current pipeline does not summarize the report or print the results in any meaningful way. 

Futhermore the tests are hard to understand, very long, and do not test actual use cases. I spent like 30 minutes write a test that demonstrates how RSpec works

```
require_relative '../lib/core'

RSpec.describe Core, "#read_settings" do	
	context "when settings file exists" do 
		it "returns the contents of the found settings file" do
			settings_file = File.join(File.dirname(__FILE__), '../default_settings.yml')
			arguments = { '--settings' => "#{settings_file}" }
			file_parsed = Core.read_settings_file(arguments)
			expect(file_parsed).not_to be_nil
		end
	end
	context "when settings file does not exist" do 
		it "throws an exception with description" do 
			settings_file = File.join(File.dirname(__FILE__), '../../default_settings_not.yml')
			arguments = { '--settings' => "#{settings_file}" }
			expect { Core.read_settings_file(arguments) }.to raise_error(RuntimeError)	
		end
	end
end
```

When you run a test like this in rspec you get an output like so:

```
Core#read_settings
  when settings file exists
    returns the contents of the found settings file
  when settings file does not exist
    throws an exception with description
```

It's alot simpler and you get a REALLY nice report if you run `rspec --format=html` 

Is this something we want to do?

**Comment by buep** [comment]
I think that sound like a good idea. We have other issues on improving tests also, need maybe a coordinated effort on it.
Beside the nice report you mention is possible, we would like some way of graphing or counting number of tests for the functional ones to show graph in the build systems.
Unit test is something else, but we also want count and then coverage if we have real unit test.

**Comment by buep** [comment]
Will await a test strategy.

**Comment by buep** [comment]
@MadsNielsen I'm okay using rspec, but before further changes we need to have a plan, on how and when as well as which kind of test we should implement. I still prefer as much unit testing as possible as this runs fast.

I'll call you and @MichaelMadsen  for a meeting, as you two seems the most eager to work with Ruby so we together can form a test strategy for PAC.

**Comment by buep** [comment]
We have decided to move to rspec today and have made some testing guidelines and the first rspec tests.

**Comment by buep** [comment]
See #98
