### ISSUE TITLE
Fix failed release and bump patch version

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#94]
Related to #88 the release fails.

http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Praqmatic-Automated-Changelog%20pipeline/job/4_release_pac/

Please fix.

**Comment by buep** [comment]
And please bump minor version also

**Comment by MadsNielsen** [comment]
Ah...i was working on it before i saw your issue Bue....the new version is out, i didn't plan on pushing the release that fast...but oh well it should be out with the container now...

**Comment by buep** [comment]
OK, cool. I was just clicking release as we could as well release your fix.

We should have bumped patch-version, but never mind since you have released now. We bump it next time.

**Comment by buep** [comment]
What was your fix? I can't see any commits?

**Comment by MadsNielsen** [comment]
The issue was the jenkins config on the jenkins job, i fixed the job that makes the release. Error caused of recent upgrade of docker on our server. We can bump the patch version when we have another small update.

**Comment by MadsNielsen** [comment]
Right...I've fixed the jobdsl that corrects the error in the job on our jenkins server. This should close it :)
